var suggestions = [
    "New York",
    "Paris",
    "Tokyo",
    "Sydney",
    "Rio de Janeiro",
    "Cape Town",
    "Moscow",
    "London",
    "Istanbul",
    "Mumbai",
    "Bangkok",
    "Rome",
    "Toronto",
    "Mexico City",
    "Cairo",
    "Buenos Aires",
    "Seoul",
    "Berlin",
    "Dubai",
    "Beijing",
];
